manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main
      path: zephyr
      west-commands: scripts/west-commands.yml
      import: true

    - name: libcanard 
      url: https://github.com/waseemr02/libcanard
      revision: master 
      path: modules/lib/libcanard

  self:
    path: kyvernitis
